import Header from "./components/Header";
import Menu from "./components/Menu";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `Jacob's PortFolio`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css2?family=Fredericka+the+Great&family=Gowun+Batang&family=Grandiflora+One&family=Nanum+Myeongjo&family=Poiret+One&display=swap"
          as="font"
          rel="preconnect"
        ></link>
      </Head>
      <body className={inter.className}>
        <Header />
        <Menu />
        {children}
      </body>
    </html>
  );
}
